apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ahaz-k8s-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ahaz-k8s-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "ahaz-k8s-controller.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "ahaz-k8s-controller.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "ahaz-k8s-controller.serviceAccountName" . }}
      autoMountServiceAccountToken: true
      volumes:
        - name: certs-volume
          persistentVolumeClaim:
            claimName: {{ .Values.controller.volumes.certs.claimName | default (printf "%s-certs" (include "ahaz-k8s-controller.fullname" .)) }}
      containers:
        - name: k8s-controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: http
          volumeMounts:
            - name: certs-volume
              mountPath: "/certdir/"
              readOnly: false
          env:
            - name: DB_IP
              value: "{{- if .Values.database.enabled }}{{ printf "%s-db.%s" (include "ahaz-k8s-controller.fullname" .) .Release.Namespace }}{{- else }}{{ .Values.controller.database.external.host }}{{- end }}"
            - name: DB_DBNAME
              value: "{{ .Values.database.name }}"
            - name: DB_USERNAME
              value: "{{ .Values.database.user }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "ahaz-k8s-controller.fullname" . }}-db-secret"
                  key: mysql-user-password
            - name: PUBLIC_DOMAINNAME
              value: "{{ .Values.controller.publicDomainName }}"
            - name: CERT_DIR_CONTAINER
              value: "/certdir/"
            - name: K8S_IP_RANGE
              value: "{{ .Values.controller.k8sIpRange }}"
            - name: TEAM_PORT_RANGE_START
              value: "{{ .Values.controller.teamPortRangeStart }}"
            - name: TEAM_BACKUP_PORT_RANGE_START
              value: "{{ .Values.controller.teamBackupPortRangeStart }}"
            - name: TEAM_BACKUP_PORT_RANGE_END
              value: "{{ .Values.controller.teamBackupPortRangeEnd }}"
            - name: LOGLEVEL
              value: "{{ .Values.controller.logLevel }}"
            - name: K8S_IMAGEPULLSECRET_NAME
              value: "{{ .Values.pullsecrets.name }}"
            - name: K8S_IMAGEPULLSECRET_NAMESPACE
              value: "{{ .Values.pullsecrets.namespace }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ahaz-k8s-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ahaz-k8s-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "ahaz-k8s-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.controller.volumes.certs.claimName | default (printf "%s-certs" (include "ahaz-k8s-controller.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ahaz-k8s-controller.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.controller.volumes.certs.storage | default "100Mi" }}
  {{- if .Values.controller.volumes.certs.storageClassName }}      # <-- CORRECT: This line now has 4 spaces
  storageClassName: {{ .Values.controller.volumes.certs.storageClassName | quote }} # <-- CORRECT: This line now has 4 spaces
  {{- end }}