apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.pullsecrets.namespace }}
  labels:
    name: {{ .Values.pullsecrets.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-pull-secrets-role
  namespace: {{ .Values.pullsecrets.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pull-secrets-rolebinding
  namespace: {{ .Values.pullsecrets.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ahaz-k8s-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: image-pull-secrets-role
  apiGroup: rbac.authorization.k8s.io
---