apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ahaz-k8s-controller.fullname" . }}-db-secret
  namespace: {{ .Values.controller.namespace.name }}
type: Opaque
data:
  mysql-root-password: {{ .Values.database.rootPassword | b64enc }}
  mysql-user-password: {{ .Values.database.userPassword | b64enc }}