name: "Linter Test"
on: [push, pull_request]

jobs:
  lint:
    name: "Run Ruff"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Execute Ruff"
        uses: astral-sh/ruff-action@v3
